version: '3.8'

services:
  app:
    build:
      context: ./taho
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-net

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: HouseHoldAccount
      MYSQL_ROOT_PASSWORD: 168168
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --port=3306
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-net:
