spring:
  datasource:
    url: jdbc:postgresql://dpg-d0lv7o2dbo4c73canq50-a:5432/smart_manage_db
    username: smart_manage_db_user
    password: smart_manage_db_user
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8888
